"""PDF Export Engine - server-side PDF generation"""

from typing import List
from datetime import datetime
from app.models.paper import Paper


class PDFExportEngine:
    """Engine for generating PDFs from research papers"""

    def __init__(self):
        self._pdf_library = None
        self._try_import_pdf_lib()

    def _try_import_pdf_lib(self):
        """Try to import PDF generation library"""
        import importlib.util

        if importlib.util.find_spec("weasyprint"):
            self._pdf_library = "weasyprint"
        elif importlib.util.find_spec("xhtml2pdf"):
            self._pdf_library = "xhtml2pdf"
        else:
            self._pdf_library = None

    def _generate_html(self, paper: Paper, include_abstract: bool = True) -> str:
        """Generate HTML for PDF conversion"""
        authors = (
            ", ".join(a.name for a in paper.authors) if paper.authors else "Unknown"
        )

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>{paper.title}</title>
            <style>
                body {{ font-family: 'Times New Roman', serif; margin: 2cm; }}
                h1 {{ font-size: 18pt; text-align: center; margin-bottom: 20px; }}
                .authors {{ text-align: center; color: #666; margin-bottom: 10px; }}
                .meta {{ text-align: center; color: #888; font-size: 10pt; margin-bottom: 20px; }}
                .abstract {{ text-align: justify; margin: 20px 0; line-height: 1.6; }}
                h2 {{ font-size: 14pt; margin-top: 20px; border-bottom: 1px solid #ccc; }}
                .footer {{ position: fixed; bottom: 1cm; font-size: 8pt; color: #aaa; }}
            </style>
        </head>
        <body>
            <h1>{paper.title}</h1>
            <p class="authors">{authors}</p>
            <p class="meta">
                Source: {paper.source.upper()} | 
                Year: {paper.year or "N/A"} | 
                Citations: {paper.citations_count or 0} |
                Generated: {datetime.now().strftime("%Y-%m-%d")}
            </p>
        """

        if include_abstract and paper.abstract:
            html += f'<div class="abstract"><h2>Abstract</h2>{paper.abstract}</div>'

        html += """
        <div class="footer">Generated by Autonomous Paper Analyzer</div>
        </body>
        </html>
        """
        return html

    def export_to_pdf(self, paper: Paper, include_abstract: bool = True) -> bytes:
        """Export paper to PDF bytes"""
        if self._pdf_library is None:
            raise RuntimeError(
                "No PDF library available. Install weasyprint or xhtml2pdf."
            )

        html_content = self._generate_html(paper, include_abstract)

        if self._pdf_library == "weasyprint":
            from weasyprint import HTML

            pdf_bytes = HTML(string=html_content).write_pdf()
        elif self._pdf_library == "xhtml2pdf":
            from xhtml2pdf import pml

            pdf_bytes = pml(html_content).getvalue()

        return pdf_bytes

    def export_multiple_to_pdf(
        self, papers: List[Paper], title: str = "Research Papers"
    ) -> bytes:
        """Export multiple papers to a single PDF"""
        if self._pdf_library is None:
            raise RuntimeError("No PDF library available.")

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>{title}</title>
            <style>
                body {{ font-family: 'Times New Roman', serif; margin: 2cm; }}
                h1 {{ font-size: 20pt; text-align: center; }}
                .paper {{ margin-bottom: 30px; page-break-after: always; }}
                h2 {{ font-size: 14pt; border-bottom: 1px solid #ccc; }}
                .authors {{ color: #666; }}
                .meta {{ color: #888; font-size: 10pt; }}
                .abstract {{ text-align: justify; margin: 10px 0; }}
            </style>
        </head>
        <body>
            <h1>{title}</h1>
        """

        for i, paper in enumerate(papers, 1):
            authors = (
                ", ".join(a.name for a in paper.authors) if paper.authors else "Unknown"
            )
            html += f"""
            <div class="paper">
                <h2>{i}. {paper.title}</h2>
                <p class="authors">{authors}</p>
                <p class="meta">Source: {paper.source.upper()} | Year: {paper.year or "N/A"} | Citations: {paper.citations_count or 0}</p>
            """
            if paper.abstract:
                html += f'<p class="abstract"><strong>Abstract:</strong> {paper.abstract}</p>'
            html += "</div>"

        html += "</body></html>"

        if self._pdf_library == "weasyprint":
            from weasyprint import HTML

            return HTML(string=html).write_pdf()
        else:
            from xhtml2pdf import pml

            return pml(html).getvalue()
